### PR TITLE
Added Tiny87 and 167 support and corrected # indentations.

### PR DESCRIPTION
**Pull request by ArminJo**
Hi,
I needed the tone function for my ATtiny167 project, therefore I added it and test it carefully.
It supports pins 0 to 7 with interrupts and pins 8 to 15 with timer hardware outputs.
I did not touch the digital_pin_to_timer_PGM data, to keep the extension independent of analogWrite.

In order to understand the existing code I also corrected the broken indentation of the #if, #elif, #else, #endif directives.

It would be great if you could merge my work to your repo.

Best regards from Cologne
Armin

### CODE REVIEW

**Comment by ArminJo** [comment]
Hi,
I forgot to mention, that the pin mapping is only compatible with the new layout.
If this is a serious problem, I can add code for the old layout too.
Thanks
Armin

**Comment by SpenceKonde** [comment]
Wow, thanks, this is wonderful. I hadnt realized Tone was busted on the x7 series! 

Two things need to be fixed (by one of us) to merge this:
1. The old pinout needs to be supported
2. The trailing whitespace at the end of any line needs to be removed (see the travis results - it checks for this and other easy-to-miss code style issues) - theres at least one on line 310 of tone.cpp. 

I'm happy to deal with 2. if you sort out 1. I mean, eventually I would end up doing both, but if you deal with the first, it'll get merged that much faster. 

Thanks again!

**Comment by ArminJo** [comment]
I hope I will implement the old pinout until tomorrow evening, maybe I can ask UltaEdit to remove the trailing spaces. (I thought, that Eclipse would do this for me, but it seems I am wrong)

**Comment by ArminJo** [comment]
Ok, 
I could not sleep, so I implement the old pinout and found the Eclipse switch to remove all trailing spaces :-).
I only compiled the old layout, but have not tested it.
It should be correct, since it was quite easy to adapt.
Maybe you will have a careful look, just to be sure...
Thanks
Armin

**Comment by SpenceKonde** [comment]
Thanks!!!

**Pull request merged**
