### PR TITLE
Fixed ATtiny26 support

### PR DESCRIPTION
**Pull request by vitark**
Added ATtiny26 sections into avrdude.conf. 
Fixed fuses in board.txt for the MCU
Refactored Clock Source+Speed menu.
Refactored BrownOut Detect menu
Added .gitignore

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Thanks but um.... boards.txt is not hand generated in 2.0.0-dev which will
be 2.0.0 (the next release) it's generated by that heinous bad python file
in extras/development....

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***

**Comment by vitark** [comment]
I see. No problem. 
I did some work to make ATtiny26 workable for my project and just share the results. Maybe some part of the work will be useful for you) 
Thank you for the project.

**Comment by vitark** [comment]
BTW: I able to put that changes in the python generator, and provide new PR. Should I do it?

**Comment by SpenceKonde** [comment]
Oh hell yes you should <3 <3 <3

**Comment by vitark** [comment]
Hello @SpenceKonde
Changes for ATtiny26 were added to the generator. 
Due to ATtiny26 not same as other MCUs, especially clocking and BOD stuff, I have added additional options to the script:

-  **notunedclocks** -- disable generation of clocks defaults (_tunedclocks_ and _tune8stdclk_). Only defined in "internalclock" will be used.

 - **bodmenu** -- provides the possibility to define own BOD menu instead of predefined.

Both options are optional and can be used for other MCUs or omitted. 

_avr/extras/development/boards.txt_ - generated by updated script.
_avr/boards.txt_ - copy of avr/extras/development/boards.txt

**Comment by SpenceKonde** [comment]
HELL YES! AND YOU EVEN FIXED THE CONFIG GENERATOR TOO? 

You da man!

**Pull request merged**
