### PR TITLE
add ponyser programmer

### PR DESCRIPTION
**Pull request by philippG777**

### CODE REVIEW

**Comment by philippG777** [comment]
Thank You for the work on ATTinyCore!

I just added a few lines in avr/programmers.txt to support ponyser-programmers.

**Comment by beicnet** [comment]
@philippG777 This adapter will work, right? [http://core.st/projects/Serial_programmer/](http://core.st/projects/Serial_programmer/)

**Comment by philippG777** [comment]
Yes, this adapter should work with the ponyser-programmer.

**Comment by beicnet** [comment]
@philippG777 Thank you! ;)

**Pull request merged**
