### PR TITLE
Enable C++17 support

### LINKED ISSUE #557: Enable C++17 support
<details><summary>Problem: RAM and PROGMEM (click to expand)</summary><P/>

ATTiny devices are extremely constrained in RAM.  This makes it critical to get as much data into `PROGMEM` as possible.  However, `PROGMEM` requires use of special accessor functions to get data into RAM for immediate use (else user is forced to write tons more code for all use of the data).  Moving data into `PROGMEM` requires that the data be evaluated at compilation time, so the data can be placed in ROM.  Thus, the more robust support the compiler provides for `constexpr`, the more data that can be determined at compile time, thus saving precious RAM. 
</details><HR/>

<details><summary>Why C++17Trivial changes to enable (click to expand)</summary><P/>

C++17 greatly improves not only `constexpr` capabilities, but also relaxes template restrictions, allowing simpler metaprogramming that is sometimes necessary to (politely) explain to the compiler that the data really and truly is a compile-time constant.

</details><HR/>

<details><summary>Platform.txt change summary (click to expand)</summary><P/>

`avr-gcc` doesn't support `-std=c17`, but it does not matter.  Per [docs](https://gcc.gnu.org/onlinedocs/gcc/Standards.html#C-Language), `-std=c11` is treated identically to `-std=c17`.  So, no update to `CFLAGS`.

> A version with corrections integrated was prepared in 2017 and published in 2018 as ISO/IEC 9899:2018; it is known as C17 and is supported with -std=c17 or -std=iso9899:2017; the corrections are also applied with -std=c11, and the only difference between the options is the value of __STDC_VERSION__.

`CPPFLAGS` has two changes:  First, the change from `-std=gnu11` to `-std=c++17`, for the stated reasons.

Second is the addition of `-fno_sized_deallocation`, since it's not a relevant feature for ATTiny and addresses the following compiler warning:

```
...\hardware\avr\1.5.2\cores\tiny\new.cpp:29:6:
    warning: the program should also define
        'void operator delete(void*, unsigned int)'
        [-Wsized-deallocation]

 void operator delete(void * ptr) {
      ^~~~~~~~
```

</details><HR/>

The good news:
Initial compilations for ATTiny85 appear to generate identical assembly listings and .HEX files.

Please consider updating to support C++17 ... it will make seeding data in `PROGMEM` much easier.

Thank you!

### PR DESCRIPTION
**Pull request by henrygab**
Fixes #557

### CODE REVIEW

**Comment by SpenceKonde** [comment]
I think in any event, this requires running the CI builds. Which means we need github actions for CI, because travis requires money if I want to get it to run with useful level of frequency, and that it'll likely be tested on megaTinyCore first, the only one of my cores with working CI.

**Comment by henrygab** [comment]
Thanks for considering this change.

**_Do you want me to see if I can get a GitHub CI build working?_**

The GitHub [pricing page](https://github.com/pricing) indicates that (at least) the first 2000 minutes of build / month are free.

If yes, I could try to use/follow the [adafruit guide](https://github.com/adafruit/ci-arduino).

Let me know your thoughts.

P.S. - From some limited (manual) test builds using ATTiny85, the compiled assembly and .hex files were identical before/after this change.  So, while not exhaustive, that's a good sign.

**Comment by sleemanj** [comment]
> P.S. - From some limited (manual) test builds using ATTiny85, the compiled assembly and .hex files were identical before/after this change. So, while not exhaustive, that's a good sign.

I think I'm with @SpenceKonde if there is no difference in the result, then.... why is the change proposed.  

I think you should provide a solid working example case of how your change produces a better result, be it that it produces a better (smaller, faster, whatever metric) compiled result, or enables you to use a better (smaller, clearer, simpler, whatever metric) source code.

My grandma always said "don't fix what's not broke".

**Comment by henrygab** [comment]
It enables code to be written that uses constructs that are simply not allowed in C++11.

For example, look at the constraints applied to `constexpr` functions in C++11.  These were greatly relaxed in C++14.

That alone is worth the update.

**Comment by henrygab** [comment]
The web is full of examples of C++11 vs C++14 `constexpr` functions.  As to why `constexpr` functions are important here... it's to help move data into PROGMEM.

**Comment by SpenceKonde** [comment]
Regarding the github actions CI stuff - that limit on minutes/month is only for private repos! On public ones... they don't charge! It's kind of crazy!

**Comment by SpenceKonde** [comment]
Woah, all those markdown fixes, thank you! IS that an automated tool you use to check the .md files? (so I could run it against the other two cores?

**Comment by SpenceKonde** [comment]
Also euhm., you're making PR's against a branch that will never again produce a builld. Everything is getting replaced with what's in the 2.0.0 development branch, that's the next version to be released.

**Comment by henrygab** [comment]
I use [markdownlint](https://github.com/DavidAnson/vscode-markdownlint.git), a Markdown extension for VS Code.

Since this PR was for a dead branch, I'll close it.  Thanks for the heads-up on that.  👍

**Comment by SpenceKonde** [comment]
Argh, VS code, something I have no experience with. I would very much like to run a markdown check like that on all three of my cores, Something like that ought to be part of the CI, considering how the other cores already have insanely pickty CI for everything ekse.

**Comment by henrygab** [comment]
> Argh, VS code, something I have no experience with. I would very much like to run a markdown check like that on all three of my cores, Something like that ought to be part of the CI, considering how the other cores already have insanely pickty CI for everything ekse.

Well, then I think you are in luck.  😄  The VS Code extension is based on a [NodeJS linter](https://github.com/DavidAnson/markdownlint), which also links to a number GitHub Actions checks that are fairly easy to enable.  Here's a couple:

* https://github.com/github/super-linter -- Very comprehensive Lint support for many languages
* https://github.com/xt0rted/markdownlint-problem-matcher -- Ultra-simple GitHub Action just for markdown linting

Both appear to use the same underlying rules.

Hope that helps!

**Pull request closed without merging**
