### PR TITLE
Fix for broken I2C functionality on x41 chips

### PR DESCRIPTION
**Pull request by ahshah**
- CLK/SDA Pins are swapped and comments are misleading
    - Pin swap Discussion can be viewed here:
        https://github.com/SpenceKonde/ATTinyCore/discussions/833
    - Fix recursive call: Wire.cpp in soft master / hw slave
    - SoftI2CMaster.h has some interesting code changes that I can't make heads or tails of. They also break software master functionality, changes proposed here get things working again.
    - Improved some indentation and grammar

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Thanks - let's see if this passes tests...

**Comment by ahshah** [comment]
Welcome back!

**Comment by SpenceKonde** [comment]
Take a look at the automated test results, something is wrong at 1 MHz with these changes....

https://github.com/SpenceKonde/ATTinyCore/actions/runs/10724961082

**Comment by SpenceKonde** [comment]
( Icam't test at tje moment as my parts are located at a different site.

**Comment by ahshah** [comment]
I'll try and get to it this week

**Pull request merged**
