### PR TITLE
Add millis() correction to zero long-term drift

### PR DESCRIPTION
**Pull request by cburstedde**
Hi, I just pushed a formula for MICROSECONDS_PER_MILLIS_OVERFLOW that is always right, at least when F_CPU evenly divides by 100. Should bring millis() error down for all sorts of odd frequencies.

Would you want me to add additional code that makes millis() exact at zero drift?

### CODE REVIEW

**Comment by cburstedde** [comment]
Bummer two of the tests failed. It seems to be due to an 429 HTTP error.

**Comment by SpenceKonde** [comment]
Will need to examine the impacts of this carefully (or you can) - if you're not careful around things like this you can end up with the millis ISR or micros() taking forever and a day to return. Division, especially of a `long` is insanely slow on these parts (8-bit cpu with neither hardware multiplication nor division). That's why there are all those custom implementations of micros that are intentionally inexact, and composed of bitshifts instead.

**Comment by cburstedde** [comment]
> Will need to examine the impacts of this carefully (or you can) - if you're not careful around things like this you can end up with the millis ISR or micros() taking forever and a day to return. Division, especially of a `long` is insanely slow on these parts (8-bit cpu with neither hardware multiplication nor division). That's why there are all those custom implementations of micros that are intentionally inexact, and composed of bitshifts instead.

I understand.  There is no division, just an unsigned char counter/compare/add.
I can prepare the code relatively soon for you to look at it.

**Comment by cburstedde** [comment]
I've tested this with a tiny45 and F_CPU of 16 MHz (unchanged, for reference), 18 MHz and 13571490 Hz. In fact, the formulas work with arbitrary frequencies and are exact for the relevant weird ones. The ISR vector grows by 28 bytes and RAM usage goes up by 1 byte for non-power-of-two frequencies. ISR cycle growth not tested, but I have similar code integrated with @MCUdude that works fine.

Based on this, I can add a micros correction to zero drift as well. For the odd frequencies, we will save 4 bytes from RAM and make the ISR faster by 20 cycles, while micros cycles go up by a couple dozen. Just let me know.

**Comment by SpenceKonde** [comment]
Wow, thanks, that sounds great! Imo a small price to pay for getting rid of
the timing glitches.

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by cburstedde** [comment]
Ok -- it seems fine, pluse the code has been tested in a separate context. Still, if you could back me up with some testing, that would be great. I'm running this ok on an ATTiny45. Thanks for considering!

**Comment by cburstedde** [comment]
That last commit includes a long multiply in micros(). If that turns out to be too expensive, it should be possible to work around it. The workaround would only affect short-term jitter, long-term drift will still be zero. The PR as is is much cleaner though.

**Comment by cburstedde** [comment]
Hi I've separated the micros and millis PRs and made this one shorter by one commit.

The one for micros is #489 and builds upon this one. This one is for millis and ready to go.

**Pull request merged**
